;;; -*- coding: utf-8; -*-

(in-package :jp-numeral.test)

(defun test-normal ()
  (assert-progn
    (equal "〇" (format nil "~/jp-numeral:jp/" 0))
    ;; 1-9
    (equal "一" (format nil "~/jp-numeral:jp/" 1))
    (equal "二" (format nil "~/jp-numeral:jp/" 2))
    (equal "三" (format nil "~/jp-numeral:jp/" 3))
    (equal "四" (format nil "~/jp-numeral:jp/" 4))
    (equal "五" (format nil "~/jp-numeral:jp/" 5))
    (equal "六" (format nil "~/jp-numeral:jp/" 6))
    (equal "七" (format nil "~/jp-numeral:jp/" 7))
    (equal "八" (format nil "~/jp-numeral:jp/" 8))
    (equal "九" (format nil "~/jp-numeral:jp/" 9))
    ;; 10-19
    (equal "十" (format nil "~/jp-numeral:jp/" 10))
    (equal "十一" (format nil "~/jp-numeral:jp/" 11))
    (equal "十二" (format nil "~/jp-numeral:jp/" 12))
    (equal "十三" (format nil "~/jp-numeral:jp/" 13))
    (equal "十四" (format nil "~/jp-numeral:jp/" 14))
    (equal "十五" (format nil "~/jp-numeral:jp/" 15))
    (equal "十六" (format nil "~/jp-numeral:jp/" 16))
    (equal "十七" (format nil "~/jp-numeral:jp/" 17))
    (equal "十八" (format nil "~/jp-numeral:jp/" 18))
    (equal "十九" (format nil "~/jp-numeral:jp/" 19))
    ;; 20-99
    (equal "二十" (format nil "~/jp-numeral:jp/" 20))
    (equal "二十一" (format nil "~/jp-numeral:jp/" 21))
    (equal "二十九" (format nil "~/jp-numeral:jp/" 29))
    (equal "三十" (format nil "~/jp-numeral:jp/" 30))
    (equal "三十一" (format nil "~/jp-numeral:jp/" 31))
    (equal "三十九" (format nil "~/jp-numeral:jp/" 39))
    (equal "四十" (format nil "~/jp-numeral:jp/" 40))
    (equal "四十一" (format nil "~/jp-numeral:jp/" 41))
    (equal "四十九" (format nil "~/jp-numeral:jp/" 49))
    (equal "五十" (format nil "~/jp-numeral:jp/" 50))
    (equal "五十一" (format nil "~/jp-numeral:jp/" 51))
    (equal "五十九" (format nil "~/jp-numeral:jp/" 59))
    (equal "六十" (format nil "~/jp-numeral:jp/" 60))
    (equal "六十一" (format nil "~/jp-numeral:jp/" 61))
    (equal "六十九" (format nil "~/jp-numeral:jp/" 69))
    (equal "七十" (format nil "~/jp-numeral:jp/" 70))
    (equal "七十一" (format nil "~/jp-numeral:jp/" 71))
    (equal "七十九" (format nil "~/jp-numeral:jp/" 79))
    (equal "八十" (format nil "~/jp-numeral:jp/" 80))
    (equal "八十一" (format nil "~/jp-numeral:jp/" 81))
    (equal "八十九" (format nil "~/jp-numeral:jp/" 89))
    (equal "九十" (format nil "~/jp-numeral:jp/" 90))
    (equal "九十一" (format nil "~/jp-numeral:jp/" 91))
    (equal "九十九" (format nil "~/jp-numeral:jp/" 99))
    ;; 100
    (equal "百" (format nil "~/jp-numeral:jp/" 100))
    ;; 
    t))

(defun main ()
  (and (test-normal)
       t))
